
# container based test build at travis-ci.org

sudo: false

install:
- mkdir -vp $HOME/{tmp,build}
# JJB deps and then JJB itself
- pip install --user ordereddict 'six>=1.5.2' PyYAML 'python-jenkins>=0.4.1' 'pbr>=0.8.2,<2.0'
- './install-dependencies.sh install_jjb'

before_script:
- jenkins-jobs --version
- test -d dist || mkdir -vp dist
- mkdir -vp /etc/jenkins_jobs
- echo '[job_builder] ' >/etc/jenkins_jobs/jenkins_jobs.ini
- echo 'allow_empty_variables=True ' >>/etc/jenkins_jobs/jenkins_jobs.ini

script:
- ./jtb-process.sh tpl dist
- ./update.sh

branches:
  only:
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
- ENV=


