
# container based test build at travis-ci.org

sudo: false

install:
- pip install --user ordereddict 'six>=1.5.2' PyYAML 'python-jenkins>=0.4.1' 'pbr>=0.8.2,<2.0' stevedore==1.8.0
- mkdir -vp $HOME/{.local/{bin,lib},build}
- Build_Deps_Default_Paths=1 ./install-dependencies.sh -

before_script:
- jenkins-jobs --version
- bats --version
# TODO: git-versioning
- test -d dist || mkdir -vp dist
#- echo '[job_builder] ' > $HOME/.jenkins_jobs.ini
#- echo 'allow_empty_variables=True ' >> $HOME/.jenkins_jobs.ini

script:
- make dist test

branches:
  only:
  - '/^.*test$/'
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
- |
    ENV= 
    PATH=$PATH:$HOME/.local/bin
    TRAVIS_SKIP=1
    BATS_REPO=https://github.com/dotmpe/bats.git
    BATS_BRANCH=f_run_index
    JJB_REPO=https://github.com/dotmpe/jenkins-job-builder.git
    JJB_BRANCH=master


