
# container based test build at travis-ci.org

sudo: false

install:
- mkdir -vp $HOME/{tmp,build}
# JJB deps and then JJB itself
- pip install --user ordereddict 'six>=1.5.2' PyYAML 'python-jenkins>=0.4.1' 'pbr>=0.8.2,<2.0'
- './install-dependencies.sh install_jjb'
- './install-dependencies.sh install_bats'

before_script:
- jenkins-jobs --version
- test -d dist || mkdir -vp dist
- echo '[job_builder] ' > $HOME/.jenkins_jobs.ini
- echo 'allow_empty_variables=True ' >> $HOME/.jenkins_jobs.ini

script:
- make dist test

branches:
  only:
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
- ENV=


