
# container based test build at travis-ci.org

sudo: false

install:
- mkdir -vp $HOME/{tmp,build}
# JJB deps and then JJB itself
- source ./install-dependencies.sh && install_jjb

before_script:

script: ./test.sh && ./update.sh

branches:
  only:
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
- ENV=


