
# container based build at travis-ci.org

sudo: false

install:
- mkdir -vp $HOME/{tmp,build}

before_script:
# JJB deps and then JJB itself
- pip install --user ordereddict six>=1.5.2 PyYAML python-jenkins>=0.4.1 pbr>=0.8.2,<2.0
- source ./install-dependencies.sh && install_jjb

script: ./update.sh

branches:
  only:
  - master
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
- ENV=


