
# container based test build at travis-ci.org

sudo: false

install:
- mkdir -vp $HOME/{.local/{bin,lib},build}
- |
    BATS_REPO=https://github.com/dotmpe/bats.git \
    BATS_BRANCH=f_run_index \
    JJB_REPO=https://github.com/dotmpe/jenkins-job-builder.git \
    JJB_BRANCH=master \
    Build_Deps_Default_Paths=1  \
    ./install-dependencies.sh -

before_script:
- jenkins-jobs --version
- bats --version
- git-versioning
- test -d dist || mkdir -vp dist

script:
- make dist test

branches:
  only:
  - master
  - '/^.*test$/'
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
- |
    ENV= 
    PATH=$PATH:$HOME/.local/bin
    TRAVIS_SKIP=1


