
# container based build at travis-ci.org

sudo: false

install:
- mkdir -vp $HOME/{tmp,build}
- . ./install-dependencies.sh && install_jjb

before_script:

script: ./update.sh

branches:
  only:
  - master
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
- ENV=


