# tasks-ignore-file

- id: jtb
  main: jtb
  version: 0.0.4-dev # jtb

  environments:
  - dev

  pd-meta:
    tasks:
      tags:
        - XXX
        - TODO
        - FIXME
        - NOTE
        - BUG
      document: todo.txt
      done: .done.txt

  scripts:
    test:
      - make dist test
    bats:
      - ./test/*-spec.bats
    tasks:
      - htd tasks --Check-All-Tags --Check-All-Files

