
- defaults:
    name: base

    # Job template vars
    project-title: 'Job Template Builder'
    build-summary-image: /userContent/jenkins-build-templates.png
    disabled: true
    concurrent: true
    htmlDescription:
    restrict-node: ''

    ## Parameter vars
    # none

    ## Trigger vars
    # none

    ## Builder vars
    # none

    ## Publisher vars
    # jtb-checkstyle
    # jtb-inline-tasks-parser
    project-src:
    # jtb-std-log-parser
    log-parser-rules: $JENKINS_HOME/log-parser-rules.txt
    unstable-on-warning: true
    fail-on-error: false
    # jtb-std-email
    email-every-unstable: false
    email-individuals: false
    email-to:
    # jenkins-html
    report-files:
    # jenkins-summary
    # jtb-junit

    ## Wrapper vars
    # none

    jjb-files:

    publish-on-error: true

    git-browser:
    git-browser-url:
    credentials-id:

    git-recursive-init: false

    bats-tap-results: 'build/test-results.tap'
    bats-tap-require-tests: true
    bats-tap-fail-build: true
    bats-tap-console-output: true
    bats-tap-enable-subtests: true
    bats-tap-discard-old: true
    bats-tap-todo-is-failure: true
    bats-tap-include-diagnostics: true
    bats-tap-validate-test-number: true
    bats-tap-require-plan: true
    bats-tap-verbose: true



### JJB Action macros for job parts

#include ./builder/main.yaml
#include ./builder/generic-env-inject.yaml
#include ./builder/build-name-updater.yaml
#include ./publisher/main.yaml


### Misc parts

#include ./main.yaml
#include ./scm/git.yaml
#include ./property/generic-env-inject.yaml


## YAML aliases

#include ./wrapper/std.yaml
#include ./publisher/std.yaml



### More complex YAML aliases: composite job types
#
#include ./job/std.yaml

- private_gh_job: &private_gh_job
    name: private_gh_job
    <<: *generic_freestyle_job
    <<: *private_gh_co


- gh_job: &gh_job
    name: gh_job
    <<: *generic_freestyle_job

    #<<: *std_gh_co

    scm:
    - 'scm-{vendor-repo}-0':
        vendor-path: '{vendor-path}'
        branch: '{branch}'
        credentials-id: '{credentials-id}'


### At last, JJB templates

#include ./job-template/main.yaml
##include ./job-template/docker.yaml
#include ./job-template/workflow.yaml


# Id: jtb/0.0.3-dev tpl/base.yaml
