
- defaults:
    name: base

    # Job template vars
    project-title: 'Job Template Builder'
    build-summary-image: /userContent/jenkins-build-templates.png
    disabled: true
    concurrent: true
    htmlDescription:
    restrict-node: ''

    ## Parameter vars
    # none

    ## Trigger vars
    # none

    ## Builder vars
    # none

    ## Publisher vars
    # jtb-checkstyle
    # jtb-inline-tasks-parser
    project-src:
    # jtb-std-log-parser
    log-parser-rules: $JENKINS_HOME/log-parser-rules.txt
    unstable-on-warning: true
    fail-on-error: false
    # jtb-std-email
    email-every-unstable: false
    email-individuals: false
    email-to:
    # jenkins-html
    report-files:
    # jenkins-summary
    # jtb-junit

    ## Wrapper vars
    # none

    jjb-files:

    publish-on-error: true

    git-browser: auto
    git-browser-url:
    credentials-id:

    git-recursive-init: false

    require-tap-plan: false




### JJB Action macros for job parts

#include ./builder/main.yaml
#include ./publisher/main.yaml


### Misc parts

#include ./main.yaml
#include ./scm/git.yaml


## YAML aliases

#include ./wrapper/std.yaml
#include ./publisher/std.yaml


### Some more JJB Action macros

## SCM macro

# FIXME: test this later, using yaml alias for now
- scm:
    name: 'scm-github-0'

    <<: *std_gh_co


### More complex YAML aliases: composite job types
#
#include ./job/std.yaml

- private_gh_job: &private_gh_job
    name: private_gh_job
    <<: *std_freestyle_job
    <<: *private_gh_co


- gh_job: &gh_job
    name: gh_job
    <<: *std_freestyle_job
    <<: *std_gh_co

    #<<: *gh_co
# FIXME: test this later, using yaml alias for now
#    scm:
#    - 'scm-github-0':
#vendor-path: '{vendor-path}'
#    branch: '{branch}'


### At last, JJB templates

#include ./job-template/main.yaml

# Id: jtb/0.0.2-test tpl/base.yaml
