
#
# The initial base file, split this up later.
#


- defaults:
    name: base

    # Job template vars
    title: 'Job Template Builder'
    build-summary-image: /userContent/jenkins-build-templates.png
    disabled: true

    ## Builder vars

    ## Publisher vars
    # jtb-checkstyle
    # jtb-inline-tasks-parser
    project-src:
    # jtb-std-log-parser
    log-parser-rules: /var/lib/jenkins/log-rules.txt
    unstable-on-warning: false
    fail-on-error: false
    # jtb-std-email
    email-every-unstable: false
    email-individuals: false
    email-to:
    # jenkins-html
    report-files:
    # jenkins-summary
    # jtb-junit



### JJB Action macros for job parts


## Builder macros

- builder:
    name: jtb-0-builder
    builders:
    - shell: 'jenkins-jobs test'


## Publisher macros


- publisher:
     name: jtb-checkstyle
     publishers:
     - checkstyle:
         pattern: 'build/checkstyle-result.xml'


- publisher:
     name: jtb-inline-tasks-parser
     publishers:
     - task-scanner:
         pattern: '{project-src}'
         health-threshold: low
         can-run-on-failed: true
         use-stable-build-as-reference: false
         use-delta-values: false
         should-detect-modules: false
         do-not-resolve-relative-paths: true
         dont-compute-new: true


- publisher:
    name: jtb-log-parser
    publishers:
    # hudson.plugins.logparser.LogParserPublisher
    - logparser:
        parse-rules: '{log-parser-rules}'
        unstable-on-warning: '{unstable-on-warning}'
        fail-on-error: '{fail-on-error}'


- publisher:
    name: jtb-std-email
    publishers:
    # use hudson.tasks.Mailer, see also hudson.maven.reporters.Mailer
    - email:
        notify-every-unstable-build: '{email-every-unstable}'
        send-to-individuals: '{email-individuals}'
        recipients: '{email-to}'


- publisher:
    name: jenkins-html
    publishers:
    - html-publisher:
        name: 'JTB Build Report'
        dir: build/ci-html-report/
        files: '{report-files}'
        keep-all: true
        allow-missing: true


- publisher:
    name: jenkins-summary
    publishers:
    - xml-summary:
        files: 'test_summary.xml'


- publisher:
    name: jtb-junit
    publishers:
    - junit:
        results: 'build/logs/*.xml'
        keep-long-stdio: true
        test-stability: false
        claim-build: false



# JJB template

- job-template:

    name: '{name}-jtb-0'
    project-type: freestyle

    display-name: '{title}'
    disabled: '{obj:disabled}'
    description: 'TODO'

    builders:
    - jtb-0-builder

    publishers:
    - jtb-std-email:
        email-every-unstable: '{email-every-unstable}'
        email-individuals: '{email-individuals}'
        email-to: '{email-to}'
    - jtb-inline-tasks-parser:
        project-src: '{project-src}'
    #- jtb-html
    #- jtb-summary
    #- jtb-checkstyle$
#    - jtb-log-parser:
#        log-parser-rules: '{log-parser-rules}'
#        unstable-on-warning: '{unstable-on-warning}'
#        fail-on-error: '{fail-on-error}'

# Id: jtb

